on: [push]

name: CI for 'loc' and related libraries

jobs:
  build:
    name: Build and test all the packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ghc: ['8.4', '8.6', '8.8', '8.10', '9.0', '9.2']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', 'configurations/ghc-${{ matrix.ghc }}.project') }}
          restore-keys: |
              ${{ runner.os }}-${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: cabal build all --project-file ./configurations/ghc-${{ matrix.ghc }}.project

      - name: Test
        run: cabal test all --enable-tests --project-file ./configurations/ghc-${{ matrix.ghc }}.project
